name: Run MATLAB Script on GitHub-Hosted Runner
on: [push]
jobs:
  cc4m-job:
    name: Run MATLAB Script
    runs-on: ubuntu-latest
    steps:
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: report.sarif.json
