name: Run CC4M
on: [push]
jobs:
  cc4m-job:
    name: Run MATLAB Script
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Upload quality SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: report.sarif.json
          category: quality
      - name: Upload Compatibility
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: compatibility.sarif.json
          category: compatibility
